### ISSUE TITLE
Status Code 403 and status message - Forbidden

### ISSUE THREAD

**Issue by MukFlex** [Koredotcom/android-kore-sdk#1]
I am unable to connect to url, after debugging I  get status code 403 with error message Forbidden in parseHTTPStatus method WebSocketReade class.

But when I try to connect with same url  in other project then it work. It also work in IOS.
https://github.com/njovy/AppRTCDemo ( Please check in libs).

Please suggest what going wrong.

**Comment by SrinivasaraoYa-Kore** [comment]
Looks like issue with JWT token. Recheck with valid JWT token
