### ISSUE TITLE
Invalid Access Token Error

### ISSUE THREAD

**Issue by AnDev2804** [Koredotcom/android-kore-sdk#44]
![imagen_2024-10-09_163807084](https://github.com/user-attachments/assets/0effcfb4-5b74-4cb7-8bd3-602b5c7d74be)
![image](https://github.com/user-attachments/assets/b12ef40e-874c-47d0-beef-ec037752b07f)

This error occurs when I initialize the bot correctly and then proceed to change the theme from dark to light (or vice versa) of my phone and try to restart the bot with the scroll down action to reload the bot, but instead of reloading it gets the error I attached and stays in an infinite loop of loading or even sometimes the app closes. Can someone help me with this error?

**Comment by SudheerJa-Kore** [comment]
@AnDev2804 As per the screenshots provided, we can see it has the token issue can you kindly share us complete Api request along with response so that we can guide you.

**Comment by AnDev2804** [comment]
@SudheerJa-Kore Ok, thanks for telling me a little bit about what the error is about, how could I provide you with that information? Is it a specific log that is inside the packages or would I have to make a specific log to provide you with that information?

**Comment by SudheerJa-Kore** [comment]
@AnDev2804 You have posted the error response right on the above the Api url and request will be printed no need place additional logs just above the response sdk will print API(Url), request, headers and response kindly send it.

**Comment by AnDev2804** [comment]
@SudheerJa-Kore Here are some screenshots at the moment when I change the theme from dark to light on my phone
![image](https://github.com/user-attachments/assets/070179fc-7c49-425b-b1e7-3b4e2e6a56c3)
![image](https://github.com/user-attachments/assets/1093936e-7d3e-485c-97c2-d4dffef3f93d)
![image](https://github.com/user-attachments/assets/d53d34f2-9f40-454b-aab5-56e939921977)

Here are the one that are at the moment that I do the PullToRefresh
![image](https://github.com/user-attachments/assets/bebbe594-1bbe-4088-a56a-6f5bff06e7d9)

I hope it helps!

**Comment by SudheerJa-Kore** [comment]
@AnDev2804 As observed in the screenshot when you change the mobile theme from dark to light or vice versa bot is getting disconnected (You can see the linear progress bar below of the header) at that time when you pull the screen (Pull to refresh is only used to get the history messages not to refresh the screen) access token is becoming null so that you are getting "Invalid access token" error.

Hope this helps else we can connect once to look into it. Kindly update your convenient time so that will send you an invite.

**Comment by AnDev2804** [comment]
@SudheerJa-Kore Here you have my skype https://join.skype.com/invite/h2hrpuEMfLJG so you can write me there, also thank you very much for clarifying me better what the error is about, now I have a better idea on how to solve it.
