### ISSUE TITLE
Reconnection Looping into infinity cycle 

### ISSUE THREAD

**Issue by ingjuanocampo** [Koredotcom/android-kore-sdk#7]
Currently, we are facing a problem (ANR) when the bot gets disconnected and the reconnection system starts running. 

The problem happens when there is an internet connection and the URL of the bot is not reachable. (Let's say it is available via VPN and the VPN is not connected) 

```
 mConnection.connect(url, new  WebSocketConnectionHandler() {
                    @Override
                    public void onOpen() {
                        Log.d(LOG_TAG, "Connection Open.");
                        if (socketConnectionListener != null) {
                            socketConnectionListener.onOpen(isReconnectionAttaempt);
                        }
                        startSendingPong();
                        mReconnectionCount = 1;
                        mReconnectDelay = 1000;
                    }

                    @Override
                    public void onClose(int code, String reason) {
                        Log.d(LOG_TAG, "Connection Lost.");
                        if (socketConnectionListener != null) {
                            socketConnectionListener.onClose(code, reason);
                        }
                        if(timer != null){
                            timer.cancel();
                            timer = null;
                        }
                        if (isConnected()) {
                            stop();
                        }
                        if(Utils.isNetworkAvailable(mContext))
                            reconnectAttempt();
                    }

                    @Override
                    public void onMessage(String payload) {
//                        Log.d(LOG_TAG, "onTextMessage payload :" + payload);
                        if (socketConnectionListener != null) {
                            socketConnectionListener.onTextMessage(payload);
                        }
                    }
```

As you can see in this code, which is part of the `SocketWrapper.java`  the reconnection will schedule a reconnection attempt if there is internet, but as the URL is not reachable the attempts are going to be useless and they will consume the resources of the device. 

We tried to set `setmIsReconnectionAttemptNeeded(false)` but the connection is not possible with that config. 

# My recommendation is: 

* Add a limit for the number of attempts to reconnect (Which can be configurable externally) 
* Create a method that works to stop the reconnection looping 
* Make sure the reconnection attempts never run on UI thread 
* Review why setting this `setmIsReconnectionAttemptNeeded(false)`   the bot never connects

**Comment by SrinivasaraoYa-Kore** [comment]
Attempts to reconnect can be configurable externally.
start/stop method already exists
Reconnection never run on UI thread

**Comment by SrinivasaraoYa-Kore** [comment]
Use shouldAttemptToReconnect public method to setmIsReconnectionAttemptNeeded flag.
