### ISSUE TITLE
Migrate Kore ai to use AndroidX artifacts

### ISSUE THREAD

**Issue by ingjuanocampo** [Koredotcom/android-kore-sdk#8]
Android support libraries are not maintained anymore
https://developer.android.com/topic/libraries/support-library

How to migrate to AndroidX:
https://developer.android.com/jetpack/androidx/migrate

**Comment by SrinivasaraoYa-Kore** [comment]
Latest https://github.com/Koredotcom/android-kore-sdk repository migrated to androidX
